apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: draft-router-api
  name: draft-router-api
spec:
  ports:
  - name: "3156"
    port: 3156
    targetPort: 3156
  selector:
    service: draft-router-api
status:
  loadBalancer: {}
