apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: publishing-e2e-tests
  name: publishing-e2e-tests
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: publishing-e2e-tests
status:
  loadBalancer: {}
