apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: static
  name: static
spec:
  ports:
  - name: "3013"
    port: 3013
    targetPort: 3013
  selector:
    service: static
status:
  loadBalancer: {}
