apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: draft-content-store
  name: draft-content-store
spec:
  ports:
  - name: "3100"
    port: 3100
    targetPort: 3100
  selector:
    service: draft-content-store
status:
  loadBalancer: {}
