apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: nginx-proxy
  name: nginx-proxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: nginx-proxy
status:
  loadBalancer: {}
