apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: nginx-proxy
    spec:
      containers:
      - image: jwilder/nginx-proxy:latest
        name: nginx-proxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /tmp/docker.sock
          name: nginx-proxy-claim0
        - mountPath: /app/nginx.tmpl
          name: nginx-proxy-claim1
      restartPolicy: Always
      volumes:
      - name: nginx-proxy-claim0
        persistentVolumeClaim:
          claimName: nginx-proxy-claim0
      - name: nginx-proxy-claim1
        persistentVolumeClaim:
          claimName: nginx-proxy-claim1
status: {}
