apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: db
    spec:
      containers:
      - image: postgres:9.6
        name: db
        resources: {}
      restartPolicy: Always
status: {}
